/**
 * Turns seed/sites.csv and seed/users.csv into SQL for D1.
 *
 *   npm run seed                          # validate and print, changing nothing
 *   npm run seed -- --out seed/seed.sql   # write it out
 *   npx wrangler d1 execute mintsoft-portal --local --file seed/seed.sql
 *
 * It never writes to the database itself. It validates, then produces SQL you can read
 * first — which matters, because these two files decide who can sign in and which sites
 * they can order for. Re-running is safe: every statement upserts.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { CsvError } from '../src/lib/csv.ts'
import { buildSeedSql } from '../src/lib/seed-sql.ts'

const args = process.argv.slice(2)
const outIndex = args.indexOf('--out')
const outPath = outIndex >= 0 ? args[outIndex + 1] : undefined
const dir = new URL('../seed/', import.meta.url).pathname

let sitesText: string
let usersText: string
try {
  sitesText = readFileSync(`${dir}sites.csv`, 'utf8')
  usersText = readFileSync(`${dir}users.csv`, 'utf8')
} catch {
  console.error(
    'Could not read seed/sites.csv and seed/users.csv.\n' +
    'Copy the .example.csv files beside them, fill them in, and run again.\n' +
    'The real files stay out of git because they carry staff email addresses.',
  )
  process.exit(1)
}

let result
try {
  result = buildSeedSql(sitesText, usersText)
} catch (err) {
  console.error(err instanceof CsvError ? `\n${err.message}\n` : err)
  process.exit(1)
}

if (result.problems.length) {
  console.error(`\n${result.problems.length} problem(s) found. Nothing was written.\n`)
  for (const p of result.problems) console.error(`  ${p.file} line ${p.line}: ${p.message}`)
  console.error('\nFix the CSV and run again.\n')
  process.exit(1)
}

const sql = [
  '-- Generated by scripts/seed.ts. Re-running is safe: every statement upserts.',
  '-- Apply with: npx wrangler d1 execute mintsoft-portal --local --file seed/seed.sql',
  '',
  ...result.statements,
  '',
].join('\n')

if (outPath) {
  writeFileSync(outPath, sql)
  console.log(`Wrote ${result.statements.length} statement(s) to ${outPath}`)
} else {
  console.log(sql)
  console.error(`\n${result.statements.length} statement(s). Re-run with --out <file> to save them.`)
}
